### ISSUE TITLE
Battle.net and Destiny 2: SC configuration only working for Battlenet not Destiny

### ISSUE THREAD

**Issue by jsphonorio** [WombatFromHell/OriginSteamOverlayLauncher#15]
I recently tried setting up my steam controller for Destiny 2 and I found my way here. I followed the directions from the readme for the normal set up as well as directions about battlenet in the Wiki.

Unfortanutely GLoSC does not work for me on my computer(have tried multiple times but just wont work).

I did the following:
1.OSOL in my battlenet folder,
2. Ran it and set the game and launcher path/executable
3. Changed the Launchermode to URI and put in the battlenet://DST2
4. Added it to steam and named it destiny 2 so I could pick the correct controller configuration

When I launch it, it opens Battlenet and my configuration is working in that screen. When Destiny 2 opens automically about 10 seconds later, it flips back to the desktop configuration

Ill admit I'm new to the SC and I notice in the wiki it says if you cant use GLoSC you must use the "desktop mode of BPM" I wasn't sure if that mean I can't run games from BPM or if I had to use the desktop configuration.

**Comment by WombatFromHell** [comment]
It just means that you need to customize the Desktop config of the controller to match your Destiny 2 config. The Desktop config is the config that's applied when you're not in a game/BPM. 

When you're using the Desktop configuration  Steam doesn't need to hook into the game in order to pass input to it, because the controller will act like a regular keyboard and mouse.

I would look more into why GloSC isn't working for you. GloSC can fill in the compatibility gaps of the Steam Controller.

**Comment by jsphonorio** [comment]
Okay, I have it semi working using GLoSC. Not sure why it wasn't working before but a reinstall or three got it working
