### ISSUE TITLE
Overlay not working properly with Battlefront II (2017)

### ISSUE THREAD

**Issue by MolochBaal** [WombatFromHell/OriginSteamOverlayLauncher#18]
I've followed all the steps, but when I try to launch Battlefront II with the overlay, it just won't work. In Steam, I get the "xxxxx in non-steam game" and it stays there until I close the game, but then I can't open de overlay with the usual shift+tab.

**Comment by WombatFromHell** [comment]
Are you using an AMD GPU? Any 3rd party overlays or antivirus like Afterburner or Bitdefender?

**Comment by MolochBaal** [comment]
Yes, I have a Radeon HD7950, and Avast open.

**Comment by WombatFromHell** [comment]
Try disabling the AMD External Events Utility service and try the overlay again (Ctrl+Shift+Esc to open Task Manager, go to the Services tab, right click the service in question and click Stop).

If that doesn't have any effect try adding an exclusion for the Steam folder and the game folder in your antivirus settings (if applicable).

**Comment by MolochBaal** [comment]
Tried all that, same as before.

**Comment by WombatFromHell** [comment]
Have you tried temporarily uninstalling or disabling your third party antivirus if you haven't already?

Some antivirus prevent software like Steam and Origin from hooking another proccess' memory to inject an overlay. Bitdefender is known to cause issues, but Avast may also be causing problems.

Does the overlay work when not launching through Steam?

**Comment by MolochBaal** [comment]
Tried closing Avast completely. Same result.
When I launch directly from the exe, I don't even get the "in non-Steam game" message.

**Comment by WombatFromHell** [comment]
Sadly, it's pretty normal for some machines to have difficulty getting the Origin overlay and Steam overlay to work together due to the combination of video drivers and applications running on the machine. The only other things I can recommend is to maybe reinstall your video drivers and disable the Origin overlay. It's pretty normal for some machines to have difficulty getting Origin and Steam's overlays to work together, and you'll generally be forced to disable Origin's overlay in that case.

I'm sorry I can't be more helpful, but if you're not having luck after disabling common applications that can interfere then you only have [GloSC](https://github.com/Alia5/GloSC/releases) left as an option. Fortunately, GloSC and OSOL work fine together if you use OSOL as the target in your GloSC shortcut (if you're wanting to manage the launcher post-launch).

**Comment by BarterClub** [comment]
Have you turned off origin in game overlay. Origin does not like steam at the same time so orgin overrides steam.

**Comment by MolochBaal** [comment]
Yes, the Origin overlay was already disabled, it was the first thing I did.
I'll try GloSC, then. Thanks anyway :)

**Comment by MolochBaal** [comment]
Just a quick update: I managed to make it work with GloSC, which turned out to be exactly what I needed, because I do have a Steam Controller.
Thanks for forwarding me to them :D

P.S.: Do I close the thread? I don't use github that frequently '^_^

**Comment by WombatFromHell** [comment]
Glad you managed to find a solution.
