### ISSUE TITLE
Battle.net client broke URI launch

### ISSUE THREAD

**Issue by dafzor** [WombatFromHell/OriginSteamOverlayLauncher#27]
The battlenet://<game> URI no longer launches the game, you can see [bnetlauncher quick n' dirty hack in the altlaunch branch](https://github.com/dafzor/bnetlauncher/blob/altlaunch/bnetlauncher/BnetClient.cs#L421).

Just letting you know.

**Comment by WombatFromHell** [comment]
Thanks for the heads up. I'll get it fixed ASAP.

**Comment by WombatFromHell** [comment]
Fixed in commit fd4b5122. I really appreciate you pointing me to your workaround. Here's hoping Blizzard gets around to fixing their client internals.

**Comment by dafzor** [comment]
Even better workaround pointed to me in [issue comments](https://github.com/dafzor/bnetlauncher/issues/22#issuecomment-399788430).

**Comment by WombatFromHell** [comment]
I agree, the second workaround is less hacky than the first. I'll implement it when I get some free time. 

Thanks again for the heads up.

**Comment by dafzor** [comment]
Not sure it would require additional codding effort from you, maybe just some documentation changes on how to add battle.net client games.

**Comment by WombatFromHell** [comment]
It will probably take a bit of refactoring for OSOL to handle this sort of thing in a less brittle way. The way I'm handling URIs is very rudimentary right now as it assumes the launcher properly supports URI handlers and clearly Battle.net isn't behaving as it should. It's a little bit frustrating that the Battle.net launcher team decided that instead of fixing their URI handler support they've decided to move to another method of commanding their launcher that's more deeply wired (and probably also cross-platform rather than relying entirely on Windows' URI protocol support).

Either way, I'm in the process of revamping chunks of OSOL's process launcher code so I'll just toss this one on the pile. I don't mind the extra effort since the benefits will transfer to other launchers that don't properly behave with URI handlers.

**Comment by WombatFromHell** [comment]
This issue should be addressed by commit 8a5f7483d017474c722d1ed732c74291b59f8fa7 which should be included in an upcoming point release due out in a few days. Again, the cross-project cooperation is extremely appreciated (excellent work pulling out the command strings by @Ethan-BB).

**Comment by WombatFromHell** [comment]
OSOL v1.07c with the commit mentioned above has been deployed so I'm going to go ahead and close this issue. Thanks again for the help @Ethan-BB and @dafzor.
