### ISSUE TITLE
FIFA 19

### ISSUE THREAD

**Issue by massatt212** [WombatFromHell/OriginSteamOverlayLauncher#33]
When i launch the shortcut origins opens FIFA comes up and then origins crashes or reboots and game doesnt launch (Launcher skip also dosnt work)

**Comment by WombatFromHell** [comment]
There's a few things you can check:

* It could be a third-party overlay (RTSS/MSI Afterburner is one example) you have running on your system that might be causing Origin to crash. Disable any third-party overlays aside from Steam (including Origin's overlay, to start with).
* Double check that you aren't using a third-party antivirus or anti-malware. Many antivirus/anti-malware products can cause problems with overlays like Steam and Origin.
* If you haven't already, try to make sure you've updated your display drivers.
* Delete your OSOL ini file and try the OSOL setup process again, make sure to choose the game executable itself (not any launchers found in the game directory, if applicable).

**Comment by WombatFromHell** [comment]
You might also try tweaking the OSOL ini file generated for this particular game found in the directory you're running OSOL from. You could try changing the following .ini option: `PreGameLauncherWaitTime` which is set to 12 by default, if your machine takes awhile to load Origin and then the game you might try raising this to 15 or even 30. This will cause OSOL to wait that many seconds before attempting to launch the game, in order for its parent launcher to finish loading.

Otherwise, OSOL will think that the launcher has encountered an error and will immediately exit both the launcher and the game process (if any exist).

**Comment by massatt212** [comment]
i ran steam as Admin and it worked
sorry for the late reply
And i notice the GoG Client doesnt auto exit when using this launcher

**Comment by WombatFromHell** [comment]
Since you've resolved your issue I'll go ahead and close this. I've added a note to the v1.08 tasklist so I remember to investigate the GOG Launcher misbehaving when launched via OSOL.
