### ISSUE TITLE
Glyph launcher (Command line arguments)

### ISSUE THREAD

**Issue by Eduardo-Thiesen** [WombatFromHell/OriginSteamOverlayLauncher#49]
I'm trying to get steam overlay in Archeage Unchained (not the steam version). Glyph launcher doesn't run archeage.exe, it instead runs EasyAntiCheat's launch_game.exe, which seems to then run archeage.exe passing some parameters (ex -eac_launcher_settings settings_64.json -t+auth_ip xxx.xx.xx.xxx -auth_port xxxx -handle xxxxxxxxxxxxxxxx -lang en_us -glyphid xxxx -lang en_us).

I've been looking into older issues and it seems that the CommandLineProxy/DetectedCommandLine functionality was the way to do that, but it has since been deprecated. Is there a new way to pass these command line parameters?

This is how I've set the OSOL ini.

[Paths]
LauncherPath=D:\Glyph\GlyphClientApp.exe
GamePath=D:\Glyph\Games\AAUnchained\Live\launch_game.exe
LauncherArgs=
LauncherURI=
GameArgs=
MonitorPath=D:\Glyph\Games\AAUnchained\Live\bin64\archeage.exe
PreLaunchExecPath=
PreLaunchExecArgs=
PostGameExecPath=
PostGameExecArgs=
[Options]
ReLaunch=True
SkipLauncher=False
CloseLauncher=True
AutoGameLaunch=True
MinimizeLauncher=False
ElevateExternals=False
PreGameLauncherWaitTime=15
PreGameWaitTime=0
PostGameWaitTime=0
ProcessAcquisitionTimeout=120
InterProcessAcquisitionTimeout=15
GameProcessAffinity=
GameProcessPriority=Normal
[Info]
ReleaseVersion=1.0.9.8

**Comment by WombatFromHell** [comment]
Unfortunately, there isn't a way to do this at this time. You'll have to do the login process by hand.

The CommandLineProxy feature was deprecated because many - though not all - authenticating launchers nowadays have checks to make sure the game has been launched from the authenticated launcher (usually by means of an auth string) and not through any other means. It's intended to prevent hacks and account theft.

**Comment by Eduardo-Thiesen** [comment]
If there is a way for me to get Steam Overlay inside the game I don't mind launching the game manually, however OSOL seems to never "find" the game process. I thought it was because it had to be launched from OSOL, is that not the case?

**Comment by WombatFromHell** [comment]
What happens if you add the launcher as a non-Steam game and launch Archeage that way (without OSOL)? Are you able to see the overlay in that case?

**Comment by Eduardo-Thiesen** [comment]
It doesn't work, I don't get overlay in game. Seems that steam hooks into the launcher, I get my controller config working while on the launcher but not in game.

**Comment by WombatFromHell** [comment]
Hmm, it's possible that the game is designed in a way where overlays are barred from hooking into the game at all. My only two suggestions for getting around that problem is to use a Desktop Mode config so KB&M input from the controller applies system-wide, or to use a GloSC shortcut so the overlay runs as a separate window on the desktop.

**Comment by Eduardo-Thiesen** [comment]
Alright, I'll try those suggestions. Thank you very much!
