### ISSUE TITLE
Game freezing post launch

### ISSUE THREAD

**Issue by ns412** [WombatFromHell/OriginSteamOverlayLauncher#50]
First of all — thanks for making this. It’s great to be able to play non-steam games with my family from my couch. 

I’m trying to load the Outer Worlds using Epic Launcher and it freezes post launch on the Link. The game continues to run on my PC, but the link freezes. This happens about 15-20 seconds after the game opens (and it seems to be running fine for those 15 seconds).

Do you have any idea what could fix this? Happy to provide more information if needed.

**Comment by WombatFromHell** [comment]
When you say "Link" do you mean the Steam overlay or are you talking about input from the controller in-game? If it's the latter problem, you should be able to power off/on the controller and enter/exit the overlay to get input redirected back into the game. If it's the former problem the only workarounds I'm aware of involve using GloSC because it doesn't attach the overlay to the game just the input or a customized Desktop Mode config via BPM.

I don't own The Outer Worlds on EGL (Epic Games Launcher). I'm using GloSC to launch The Outer Worlds via Xbox Game Pass (as a UWP application), but as I understand it the Epic Launcher version has minimal DRM so a simple non-Steam game shortcut should work fine.
