### ISSUE TITLE
Overlay interacts with Modern Warfare in the background.

### ISSUE THREAD

**Issue by SubSonix** [WombatFromHell/OriginSteamOverlayLauncher#53]
As above, when using the steam overlay to chat for example, it also interacts with the game.

**Comment by WombatFromHell** [comment]
This is an issue with the Steam overlay itself and how Steam handles hooking GPU accelerated launchers. I'm not aware of a workaround for this except to use GloSC.

I'm currently investigating adding a hook manager into a future version of OSOL or forking GloSC and adding OSOL's features to it (given that the GloSC project is now is maintenance-only mode).

**Comment by WombatFromHell** [comment]
I tested some possible workarounds just now and for some launchers you can get away with setting `SkipLauncher=True` and `ReLaunch=False`. This would have OSOL launch only the game (but still monitor the launcher once the game exits due to `CloseLauncher=True` being the default) and the game would usually launch its parent launcher if it isn't already running. The Steam overlay should still be able to hook the game in this situation but not always. Try it and see if it works for you.

**Comment by SubSonix** [comment]
Thanks mate, I'll give them a go later on and let you know how I go :)

**Comment by SubSonix** [comment]
No luck with those changes, this is what my .ini looks like when it's business as normal.

[Paths]
GamePath=X:\Games\Call of Duty Modern Warfare\ModernWarfare.exe
LauncherPath=C:\Programs\Battle.net\Battle.net.exe
LauncherArgs=--exec="launch ODIN"
LauncherURI=
GameArgs=
MonitorPath=
PreLaunchExecPath=
PreLaunchExecArgs=
PostGameExecPath=
PostGameExecArgs=
[Options]
ReLaunch=True
SkipLauncher=False
CloseLauncher=True
AutoGameLaunch=True
MinimizeLauncher=False
ElevateExternals=False
ForceKillExternals=False
PreGameLauncherWaitTime=5
PreGameWaitTime=5
PostGameWaitTime=5
ProcessAcquisitionTimeout=120
InterProcessAcquisitionTimeout=15
GameProcessAffinity=
GameProcessPriority=Normal
[Info]
ReleaseVersion=1.0.9.9
