### ISSUE TITLE
Origin and Battlefront 2

### ISSUE THREAD

**Issue by BarterClub** [WombatFromHell/OriginSteamOverlayLauncher#8]
The game launches but the screen is black. After some time the game ends and closes everything

**Comment by WombatFromHell** [comment]
I don't have Battlefront 2 to test against, but IIRC the black screen bug is a known issue with Battlefront 2.

Generally speaking though, if you have issues with a particular game/launcher and OSOL it's usually because you're not targeting the right executables. Other than that I would suggest removing 3rd party overlays to limit conflicts with Steam and see if that helps at all.

**Comment by BarterClub** [comment]
MSI Afterburner was the issue. Do you know a way to make both work? I use it for a custom fan curve and some other stats.

**Comment by BarterClub** [comment]
Ok so how to solve it was to have the RivaTuner detection level set to low.

**Comment by WombatFromHell** [comment]
I'm glad you got it solved.

Steam and 3rd party overlays can be tricky to get working. RTSS/Afterburner tends to work best on the default detection settings, given that Steam has some workarounds it uses to improve compatibility. There are still some overlays that can cause issues like the AMD External Events services.
